name: Wing Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write      # required for requesting the JWT
  contents: read       # required for checkout
  pull-requests: write # required for posting comments to pull requests

env:
  AWS_REGION: "us-east-1"
  TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
  TF_BACKEND_BUCKET_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gh-actions-winglang
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Plan
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: main.w
          target: 'tf-aws'